FROM alpine:3.8

RUN apk update && \
    apk add git && \
    apk add curl

WORKDIR /workspace
 
RUN chgrp -R 0 /workspace && \
    chmod -R g=u /workspace


USER 1001

ENTRYPOINT ["tail", "-f", "/dev/null"]